# Game World Hub — MSIX Build Script for Windows
# Run from the monorepo root:
#   powershell -ExecutionPolicy Bypass -File artifacts/game-world-hub-desktop/scripts/build-msix.ps1
#
# The desktop app loads https://gmes.app directly — no bundled renderer or
# API server is needed.  This script only builds the Electron shell itself.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "=== Game World Hub — MSIX Build ===" -ForegroundColor Cyan

# ── 1. Check prerequisites ────────────────────────────────────────────────────
Write-Host "`n[1/4] Checking prerequisites..." -ForegroundColor Yellow

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Error "Node.js not found. Install from https://nodejs.org"
    exit 1
}
if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
    Write-Error "pnpm not found. Run: npm install -g pnpm"
    exit 1
}
if (-not (Get-Command magick -ErrorAction SilentlyContinue)) {
    Write-Warning "ImageMagick (magick) not found — AppX tiles will be auto-generated by electron-builder."
    Write-Warning "Install via: winget install ImageMagick.ImageMagick"
}

# ── 2. Install dependencies ───────────────────────────────────────────────────
Write-Host "`n[2/4] Installing dependencies..." -ForegroundColor Yellow
pnpm install --frozen-lockfile
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

# ── 3. Generate AppX tile assets ─────────────────────────────────────────────
Write-Host "`n[3/4] Generating AppX icon assets..." -ForegroundColor Yellow
Push-Location "artifacts\game-world-hub-desktop"
if (Get-Command magick -ErrorAction SilentlyContinue) {
    node scripts/generate-appx-icons.mjs
    if ($LASTEXITCODE -ne 0) { Pop-Location; exit $LASTEXITCODE }
} else {
    Write-Host "  Skipping — ImageMagick not available; electron-builder will auto-scale icon.png." -ForegroundColor Gray
}
Pop-Location

# ── 4. Build MSIX ─────────────────────────────────────────────────────────────
Write-Host "`n[4/4] Building MSIX..." -ForegroundColor Yellow
Push-Location "artifacts\game-world-hub-desktop"
pnpm run build:win:msix
if ($LASTEXITCODE -ne 0) { Pop-Location; exit $LASTEXITCODE }
Pop-Location

# ── Done ──────────────────────────────────────────────────────────────────────
$msix = Get-ChildItem "artifacts\game-world-hub-desktop\dist-electron\*.msix" | Select-Object -First 1
if ($msix) {
    Write-Host "`n✅ MSIX built successfully:" -ForegroundColor Green
    Write-Host "   $($msix.FullName)" -ForegroundColor White
    Write-Host "   Size: $([math]::Round($msix.Length / 1MB, 1)) MB" -ForegroundColor Gray
    Write-Host "`nNext step: Upload this file to Microsoft Partner Center → Submissions → Packages" -ForegroundColor Cyan
} else {
    Write-Error "MSIX file not found after build."
    exit 1
}
