import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import friendsRouter from "./friends";
import conversationsRouter from "./conversations";
import partiesRouter from "./parties";
import lfgRouter from "./lfg";
import achievementsRouter from "./achievements";
import blocksRouter from "./blocks";
import contentRouter from "./content";
import libraryRouter from "./library";
import gamesRouter from "./games";
import platformsRouter from "./platforms";
import notificationsRouter from "./notifications";
import livekitRouter from "./livekit";
import storageRouter from "./storage";
import imagesRouter from "./images";
import proRouter from "./pro";
import challengesRouter from "./challenges";
import statsRouter from "./stats";
import lfgBotRouter from "./lfg-bot";
import proGiftsRouter from "./pro-gifts";
import adminRouter from "./admin";
import ownerRouter from "./owner";
import downloadRouter from "./download";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(friendsRouter);
router.use(conversationsRouter);
router.use(partiesRouter);
router.use(lfgRouter);
router.use(achievementsRouter);
router.use(blocksRouter);
router.use(contentRouter);
router.use(libraryRouter);
router.use(gamesRouter);
router.use(platformsRouter);
router.use(notificationsRouter);
router.use(livekitRouter);
router.use(storageRouter);
router.use(imagesRouter);
router.use(proRouter);
router.use(challengesRouter);
router.use(statsRouter);
router.use(lfgBotRouter);
router.use(proGiftsRouter);
router.use(adminRouter);
router.use(ownerRouter);
router.use(downloadRouter);

export default router;
