import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import friendsRouter from "./friends";
import conversationsRouter from "./conversations";
import partiesRouter from "./parties";
import lfgRouter from "./lfg";
import achievementsRouter from "./achievements";
import blocksRouter from "./blocks";
import contentRouter from "./content";
import libraryRouter from "./library";
import gamesRouter from "./games";
import platformsRouter from "./platforms";
import notificationsRouter from "./notifications";
import iceRouter from "./ice";
import storageRouter from "./storage";
import proRouter from "./pro";
import adminRouter from "./admin";
import ownerRouter from "./owner";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(friendsRouter);
router.use(conversationsRouter);
router.use(partiesRouter);
router.use(lfgRouter);
router.use(achievementsRouter);
router.use(blocksRouter);
router.use(contentRouter);
router.use(libraryRouter);
router.use(gamesRouter);
router.use(platformsRouter);
router.use(notificationsRouter);
router.use(iceRouter);
router.use(storageRouter);
router.use(proRouter);
router.use(adminRouter);
router.use(ownerRouter);

export default router;
