// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gwh-logos/GlitchMark.tsx": () => import("../components/mockups/gwh-logos/GlitchMark.tsx"),
  "./components/mockups/gwh-logos/HexCore.tsx": () => import("../components/mockups/gwh-logos/HexCore.tsx"),
  "./components/mockups/gwh-logos/HexForge.tsx": () => import("../components/mockups/gwh-logos/HexForge.tsx"),
  "./components/mockups/gwh-logos/HexSplit.tsx": () => import("../components/mockups/gwh-logos/HexSplit.tsx"),
  "./components/mockups/gwh-logos/PadPulse.tsx": () => import("../components/mockups/gwh-logos/PadPulse.tsx"),
  "./components/mockups/gwh-logos/PixelForge.tsx": () => import("../components/mockups/gwh-logos/PixelForge.tsx"),
  "./components/mockups/pro-badge-variants/Variants.tsx": () => import("../components/mockups/pro-badge-variants/Variants.tsx"),
  "./components/mockups/profile-variants/Overlay.tsx": () => import("../components/mockups/profile-variants/Overlay.tsx"),
  "./components/mockups/profile-variants/PlayerCard.tsx": () => import("../components/mockups/profile-variants/PlayerCard.tsx"),
  "./components/mockups/profile-variants/PremiumMix.tsx": () => import("../components/mockups/profile-variants/PremiumMix.tsx"),
  "./components/mockups/profile-variants/SplitPanel.tsx": () => import("../components/mockups/profile-variants/SplitPanel.tsx"),
  "./components/mockups/voice-panel/Apex.tsx": () => import("../components/mockups/voice-panel/Apex.tsx"),
  "./components/mockups/voice-panel/Grid.tsx": () => import("../components/mockups/voice-panel/Grid.tsx"),
  "./components/mockups/voice-panel/Halo.tsx": () => import("../components/mockups/voice-panel/Halo.tsx")
};
